/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
#define _Included_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    allocate0
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_allocate0
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    release0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_release0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    newSession0
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_newSession0
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    update0
 * Signature: (JJIJII)I
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_update0
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jint);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
