/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zlib_natives_NativeZlibDeflater
#define _Included_net_daporkchop_lib_compression_zlib_natives_NativeZlibDeflater

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibDeflater
 * Method:    allocateCtx
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibDeflater_allocate0
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibDeflater
 * Method:    releaseCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibDeflater_release0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibDeflater
 * Method:    compress0
 * Signature: (JJIJIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibDeflater_compress0
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zlib_natives_NativeZlibDeflater
