/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
#define _Included_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_load
  (JNIEnv *, jclass);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    allocateCtx
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_allocateCtx
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    releaseCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_releaseCtx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    doFullInflate
 * Signature: (JIJIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_doFullInflate
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jlong, jint);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    doUpdate
 * Signature: (JIJIJIZ)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_doUpdate
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jlong, jint, jboolean);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    doFinish
 * Signature: (JIJIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_doFinish
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jlong, jint);

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
 * Method:    doReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater_doReset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zlib_natives_NativeZlibInflater
