/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zlib_natives_NativeZlib
#define _Included_net_daporkchop_lib_compression_zlib_natives_NativeZlib

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zlib_natives_NativeZlib
 * Method:    compressBoundLong
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zlib_natives_NativeZlib_compressBoundLong
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zlib_natives_NativeZlib
