/*
 * Adapted from the Wizardry License
 *
 * Copyright (c) 2018-2019 DaPorkchop_ and contributors
 *
 * Permission is hereby granted to any persons and/or organizations using this software to copy, modify, merge, publish, and distribute it. Said persons and/or organizations are not allowed to use the software or any derivatives of the work for commercial use or any other means to generate income, nor are they allowed to claim this software as their own.
 *
 * The persons and/or organizations are also disallowed from sub-licensing and/or trademarking this software without explicit permission from DaPorkchop_.
 *
 * Any persons and/or organizations using this software must disclose their source code and have it publicly available, include this license, provide sufficient credit to the original authors of the project (IE: DaPorkchop_), as well as provide a link to the original project.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 */

package binary;import net.daporkchop.lib.binary.UTF8;
import net.daporkchop.lib.binary.stream.bit.Huffman;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;

/**
 * @author DaPorkchop_
 */
public class TestHuffman {
    /**
     * These are some random texts i found online
     */
    public static final String[] test_strings = new String[]{
            "I'd just like to interject for moment. What you're referring to as Linux, is in fact, GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising testMethodThing full OS as defined by POSIX.\n" +
                    "\n" +
                    "Many computer users run a modified version of the GNU system every day, without realizing it. Through testMethodThing peculiar turn required events, the version required GNU which is widely used today is often called Linux, and many required its users are not aware that it is basically the GNU system, developed by the GNU Project.\n" +
                    "\n" +
                    "There really is a Linux, and these people are using it, but it is just testMethodThing part of the system they use. Linux is the kernel: the program in the system that allocates the machine's resources to the other programs that you run. The kernel is an essential part required an operating system, but useless by itself; it can only function in the context required testMethodThing complete operating system. Linux is normally used in combination with the GNU operating system: the whole system is basically GNU with Linux added, or GNU/Linux. All the so-called Linux distributions are really distributions required GNU/Linux!",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam imperdiet posuere viverra. Vestibulum varius urna quis orci finibus dapibus. Nam suscipit turpis nec purus tristique, elementum convallis purus blandit. Suspendisse consectetur in mi sed accumsan. Pellentesque luctus iaculis nunc sed varius. Praesent pretium ante pretium ante dictum, a bibendum ipsum elementum. Fusce et fermentum diam. Ut et sodales lacus. Duis fermentum mauris sit amet eros posuere gravida. Donec tincidunt malesuada mi, nec ultrices ante efficitur quis. Sed condimentum laoreet interdum. Proin bibendum, augue non vestibulum cursus, erat ante vulputate purus, sed tempor leo mauris id nisi. Etiam ac ex vitae dolor pharetra gravida id testMethodThing nunc. Nam vehicula consectetur augue ac ullamcorper. Morbi molestie turpis sem, vel ultricies nulla malesuada vel.\n" +
                    "\n" +
                    "Curabitur imperdiet neque et purus tristique, at vehicula leo posuere. Vestibulum lectus quam, dictum pharetra finibus lobortis, scelerisque mollis ipsum. Aliquam eget semper lacus. Aliquam erat volutpat. Donec nec diam euismod, suscipit nisl id, vehicula nisi. Fusce faucibus erat mauris, id gravida justo ullamcorper sed. Proin et tristique sapien. Nunc at nisi porta, cursus orci ac, hendrerit nisl. Morbi porttitor ornare odio id venenatis. Mauris molestie elit semper tincidunt semper.\n" +
                    "\n" +
                    "Proin ornare vestibulum sem in iaculis. Nulla ac tincidunt metus. Praesent a nibh elit. Sed ac aliquam magna, pulvinar malesuada sem. Suspendisse ornare efficitur justo, testMethodThing vehicula massa consectetur sit amet. Ut sollicitudin ante eu egestas tincidunt. Nulla faucibus nibh augue, quis vestibulum velit efficitur at. Cras eget diam nunc. Sed orci lectus, ultricies et malesuada nec, suscipit ut libero. Cras rutrum tellus nec eleifend imperdiet. Mauris venenatis mattis urna. Sed vel sagittis nibh. Morbi vel ex est.\n" +
                    "\n" +
                    "Aenean pretium lorem quis ante vestibulum mollis. Maecenas erat erat, dapibus sed lorem ut, imperdiet mollis magna. Ut nunc urna, aliquam a aliquet sit amet, faucibus quis quam. Aenean id libero at orci sodales sodales. Sed massa nisl, dignissim ac felis ac, congue scelerisque leo. Phasellus rutrum fermentum est id pharetra. Suspendisse non velit efficitur, blandit nulla in, scelerisque sapien. Proin rutrum facilisis urna testMethodThing facilisis. In sodales scelerisque ultrices. Quisque et libero eget lectus pulvinar tristique sit amet at sem. Fusce volutpat volutpat elit non vulputate. Vivamus ornare eget augue ac posuere. Duis vitae est quis ligula scelerisque vehicula. Mauris vitae tincidunt nulla, id convallis augue. Duis id felis ornare, facilisis enim quis, malesuada mauris. Vivamus accumsan, justo ultricies interdum feugiat, urna velit malesuada mi, ac tincidunt risus risus at leo.\n" +
                    "\n" +
                    "Sed faucibus mi tortor, sed bibendum sem mollis non. Morbi volutpat volutpat tempor. Suspendisse nec ornare urna, ut molestie odio. Aenean auctor neque et lorem facilisis, vitae dignissim odio cursus. Etiam mattis tristique euismod. Suspendisse nulla arcu, pretium ut lacus eget, lobortis vehicula dui. Duis pulvinar consectetur ligula, nec convallis augue. Sed eget neque eros. Maecenas ligula leo, suscipit a ultricies ac, porta et nisl. Donec in volutpat magna. Suspendisse potenti. Morbi ullamcorper testMethodThing sapien testMethodThing accumsan. Donec eget elit pretium lacus maximus fringilla. Ut egestas pretium metus, ac efficitur nulla consectetur id. Suspendisse vel mi eu ex porttitor auctor.\n" +
                    "\n" +
                    "Suspendisse sed euismod nulla. Fusce consectetur eget orci sed venenatis. Phasellus consequat, enim vitae cursus volutpat, purus lorem fermentum lorem, a egestas libero lacus dignissim mauris. Duis maximus condimentum purus, testMethodThing dictum est suscipit et. Maecenas auctor mi quam, eget interdum turpis gravida ut. Ut rutrum enim ut tempus ultrices. Nulla mollis nec mi eget fringilla. Cras malesuada, lacus vel varius lobortis, urna sem dapibus nibh, at cursus turpis mauris hendrerit orci. Nullam fringilla turpis vel mauris sagittis condimentum. Morbi eleifend elit magna, sit amet accumsan est mattis ut. Duis at risus sapien. Sed turpis justo, suscipit sed libero vel, viverra pulvinar sapien.\n" +
                    "\n" +
                    "Quisque in lacus eget lectus auctor sollicitudin ut ut ipsum. Duis feugiat imperdiet metus, non hendrerit ligula ultricies tincidunt. Pellentesque luctus ligula nec ullamcorper tempor. Aliquam vel molestie nunc, ut molestie enim. Quisque et tellus quis odio sollicitudin gravida. Vestibulum congue tincidunt ante, in venenatis ex lacinia vel. Morbi vitae ligula odio. Etiam nec fringilla enim, vel blandit erat.\n" +
                    "\n" +
                    "Maecenas iaculis urna nec erat elementum, non tristique lectus pellentesque. In accumsan, est in dapibus congue, metus nisl fermentum purus, egestas semper sem risus ut eros. Proin maximus neque quis nisi fringilla rutrum. Duis interdum porta erat. Duis quis ultricies libero. Vestibulum eleifend tellus sed arcu consectetur, vel aliquet mi pharetra. Curabitur vel sem eleifend, accumsan mauris eu, finibus arcu. Proin eget malesuada massa. Morbi eget sapien eu lorem pulvinar vestibulum in in diam. Ut sed mauris diam.\n" +
                    "\n" +
                    "Nam faucibus tristique sapien, eu efficitur eros. Nunc ipsum ante, eleifend id tincidunt ac, posuere sit amet ante. Morbi nec ullamcorper tellus. Pellentesque in porta dui. Nunc a interdum ipsum. Nullam diam sem, suscipit ac venenatis hendrerit, sollicitudin eu erat. Donec vitae lacus magna. In ut maximus sapien. Praesent justo augue, hendrerit placerat nisl vitae, molestie tempor libero. Integer ut diam massa. Nullam risus ipsum, faucibus non mattis ac, euismod non tellus. Morbi nec consequat turpis. Nunc rhoncus feugiat nibh, eget iaculis sem laoreet sed. Nullam vitae cursus nunc.\n" +
                    "\n" +
                    "Nam cursus vulputate neque nec imperdiet. Aenean molestie vitae dui a blandit. Suspendisse quis diam et risus sagittis porttitor ut ut mauris. Vestibulum cursus vehicula libero nec sodales. Nunc nibh turpis, lacinia ac fermentum ut, tempus sed diam. Aenean sem nunc, consectetur nec nisi non, dictum fermentum felis. Quisque lacus nisi, tempus sollicitudin sem tincidunt, fermentum tempor lorem.\n" +
                    "\n" +
                    "Nullam fringilla leo libero, in pretium nisi laoreet eget. Nulla malesuada eros porta erat dapibus auctor. Donec sodales aliquam enim et volutpat. Nunc pellentesque et lorem imperdiet imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis et ultrices nulla, eu accumsan massa. Nullam rhoncus lectus ac dapibus pulvinar. Duis ornare, nibh in porta tempor, justo sapien commodo est, eu commodo tortor nulla ut purus. Nulla nec augue ac velit laoreet molestie nec in tortor. Vestibulum in suscipit ipsum.\n" +
                    "\n" +
                    "Nulla consequat ullamcorper ex, ac condimentum orci ullamcorper vitae. Ut quis purus nec arcu finibus pharetra in nec est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean ultricies sapien nec molestie dictum. Ut quis quam dictum, finibus erat a, egestas ipsum. Vestibulum libero eros, laoreet ac velit testMethodThing, tristique elementum libero. Donec ultricies arcu non efficitur finibus. Sed ex nibh, accumsan vitae tortor sit amet, maximus viverra lectus.\n" +
                    "\n" +
                    "Quisque ultricies magna enim, ac pharetra erat lacinia sit amet. Suspendisse eleifend laoreet tellus vitae maximus. Donec nec lorem vel nibh lacinia mollis a ac est. Aliquam id maximus dolor. Nunc laoreet ut lorem non sollicitudin. Sed in odio et diam pretium facilisis sed testMethodThing nunc. Integer quis dictum nisi, eu suscipit lacus. In finibus purus sed ornare iaculis. Suspendisse vulputate nisi consectetur ex suscipit sollicitudin. Pellentesque in quam lobortis, posuere nisi testMethodThing, aliquam leo. Nullam tempor molestie mattis. In nec lectus interdum, tempus ante nec, gravida arcu. Cras lectus libero, ultricies fermentum blandit in, volutpat sed enim. Praesent testMethodThing consectetur elit, id ullamcorper tellus. Integer varius leo sit amet egestas scelerisque.\n" +
                    "\n" +
                    "Aenean vehicula, mauris et faucibus fringilla, purus metus hendrerit orci, non faucibus quam lorem sed magna. Mauris sit amet imperdiet purus. Aliquam et est dignissim, lobortis libero at, hendrerit tellus. Maecenas eget hendrerit orci, at vehicula metus. Pellentesque vel fermentum ante. Maecenas ultricies, risus quis rutrum dignissim, ante velit dignissim justo, non pulvinar erat massa non quam. Donec cras amet.",
            "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why testMethodThing new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar required the resulting language is more simple and regular than that required the individual languages. The new common language will be more simple and regular than the existing European languages. It will be as simple as Occidental; in fact, it will be Occidental. To an English person, it will seem like simplified English, as testMethodThing skeptical Cambridge friend required mine told me what Occidental is.The European languages are members required the same family. Their separate existence is testMethodThing myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why testMethodThing new common language would be desirable: one could refuse to pay expensive translators. To\n" +
                    "\n",
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
                    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
                    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
                    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
                    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "Spicy jalapeno bacon ipsum dolor amet cow landjaeger ad, chuck capicola drumstick pig ut buffalo venison spare ribs shank picanha. Mollit ea venison ut, jerky sed cow alcatra. Eiusmod ad sunt laborum non strip steak pork chop biltong corned beef short ribs consectetur turkey reprehenderit. Velit ut mollit duis. Cupidatat exercitation ut pork chop. Duis dolore drumstick, nisi aliqua sunt porchetta qui fugiat sausage deserunt. Sausage ut bresaola turducken picanha nisi brisket porchetta flank ipsum fugiat pariatur.\n" +
                    "\n" +
                    "Ut nisi pastrami fatback sint, aute exercitation porchetta chuck beef ribs excepteur culpa. Adipisicing mollit cupim, frankfurter et meatloaf pariatur reprehenderit laboris laborum enim. Shoulder swine cupim burgdoggen cupidatat, in porchetta tenderloin meatball shankle meatloaf ex aliqua. Aliqua picanha qui cupidatat chicken, ad do kielbasa. Eiusmod strip steak fugiat, qui short ribs ball tip pancetta. Beef ribs strip steak ground round, magna eu fugiat ipsum ut pancetta est hamburger laborum. Pork chop nostrud tail et shank ipsum.\n" +
                    "\n" +
                    "Reprehenderit dolor porchetta beef ribs, cupidatat pork shankle dolore. Cupidatat ipsum andouille nisi, kevin in adipisicing minim beef ribs pig flank. Laboris ball tip cupidatat cupim excepteur ut picanha labore. Proident short ribs ad leberkas drumstick. Labore ham nisi cupim pariatur. Rump ground round in turducken, corned beef tri-tip tongue est elit.\n" +
                    "\n" +
                    "Proident in buffalo brisket qui ullamco tongue sint aliquip jowl. Venison fugiat bresaola et excepteur kielbasa laboris frankfurter cillum shoulder beef do. Enim veniam qui leberkas, dolore pancetta reprehenderit irure turkey pork mollit andouille porchetta short ribs. Occaecat turducken velit doner elit. Consequat ball tip occaecat ad short loin. Labore venison ham hock buffalo id.\n" +
                    "\n" +
                    "Beef et in flank swine leberkas, non rump andouille ex short loin. Pork chop ad ham hock pork loin tongue non shoulder magna quis sirloin. Tongue shankle shoulder veniam, biltong spare ribs eiusmod in cow in pariatur ullamco. Quis landjaeger in turducken, aute veniam doner sunt minim. Shoulder shank aliqua leberkas. Capicola veniam beef esse salami mollit buffalo.\n" +
                    "\n" +
                    "Pariatur salami cillum, pork chop porchetta tenderloin leberkas tail cupidatat andouille aliquip tri-tip. Dolore jerky tongue, sed fatback shank culpa incididunt est sunt. Salami culpa nulla ribeye, pork loin flank non anim in jowl meatloaf proident quis pancetta nisi. Ham hock commodo culpa ham shoulder andouille ball tip ipsum sed ribeye kielbasa pork belly elit incididunt. Leberkas jerky cow, kevin jowl culpa et. Minim dolore fugiat officia in boudin kielbasa burgdoggen t-bone capicola ea porchetta est andouille.\n" +
                    "\n" +
                    "Incididunt short loin labore ipsum anim chuck. Drumstick excepteur ground round, fatback filet mignon pancetta meatloaf tail lorem culpa chuck ut eu. Burgdoggen tail minim ipsum et hamburger. Cupim in pariatur, drumstick shankle pastrami jerky sint cupidatat. Cupim sint sed sirloin, andouille ullamco filet mignon ground round.\n" +
                    "\n" +
                    "Swine burgdoggen spare ribs sirloin prosciutto pork loin et, drumstick picanha minim. Pork belly esse nisi picanha. Drumstick dolore shankle kielbasa. Prosciutto voluptate incididunt, labore culpa pig irure esse magna laboris. Sunt porchetta velit short ribs flank.\n" +
                    "\n" +
                    "Ipsum nulla shank enim, kevin picanha boudin in beef adipisicing. Pork corned beef lorem sunt, in porchetta ut landjaeger. Capicola fatback occaecat short ribs flank. Mollit voluptate cow capicola turkey, swine ipsum enim sed velit cupidatat irure. Veniam ea esse dolore in tri-tip consequat, consectetur flank chuck shankle laborum short ribs tenderloin. Occaecat pork chop short ribs mollit dolore alcatra beef ribs qui salami meatball.\n" +
                    "\n" +
                    "Jerky pork loin nisi, consequat eu burgdoggen proident pork belly. Spare ribs dolor bresaola, id meatloaf kevin pork. Nulla cupim turducken deserunt pork loin fugiat labore tempor pig. Pork belly boudin flank, ut in pork loin cupidatat turkey biltong dolore eiusmod occaecat dolore. Nulla pork chop shankle in adipisicing do elit, pig venison prosciutto sed.\n" +
                    "\n" +
                    "Consectetur aliquip jowl, in spare ribs capicola ea pork elit meatloaf veniam. Drumstick shoulder picanha tenderloin elit consectetur, ad pork belly et meatloaf eiusmod consequat veniam esse chicken. Capicola dolore jerky, sed frankfurter consectetur meatball shoulder ham pork chop deserunt kevin beef ribs laboris. Pork pastrami turducken shankle dolor pork chop, commodo aute turkey.\n" +
                    "\n" +
                    "Turducken reprehenderit shankle corned beef proident kielbasa esse ribeye picanha sunt ground round tenderloin. Irure short loin fugiat fatback beef venison. Jerky ball tip leberkas laboris. Aliquip dolor dolore salami occaecat. Burgdoggen ut tri-tip boudin dolore anim pork consectetur. Shank laboris consequat tongue, ex exercitation meatball swine landjaeger.\n" +
                    "\n" +
                    "Shoulder ball tip chicken tongue, veniam salami corned beef tempor velit cillum occaecat et jerky eu leberkas. Tempor turkey ut consequat, est ipsum labore ut officia mollit reprehenderit beef. Strip steak meatball brisket, et laboris ad burgdoggen exercitation cow sirloin do sint velit. Doner prosciutto spare ribs tongue turducken aliquip irure sint ipsum adipisicing quis voluptate sed. Flank consectetur frankfurter labore ribeye ball tip velit prosciutto minim lorem pariatur. Et turkey tempor ground round turducken. Cillum fatback in pork belly jowl.\n" +
                    "\n" +
                    "Quis do dolore, corned beef qui porchetta short loin ut sirloin veniam pig sunt ullamco. Ullamco bacon anim doner frankfurter. Id aliquip qui sint consectetur eiusmod pork loin beef ribs in. Commodo bresaola t-bone, non ipsum turducken doner bacon minim shank tongue. Cupidatat strip steak boudin, ham hock sunt sint t-bone sausage short ribs sirloin. Ut aliqua flank consequat jerky salami. Picanha drumstick frankfurter beef short ribs ut ground round in swine short loin occaecat.\n" +
                    "\n" +
                    "Jowl cupim veniam, reprehenderit meatloaf capicola lorem flank enim officia chicken corned beef. Irure strip steak kielbasa flank officia. Elit boudin pork dolor sed aliqua, minim filet mignon biltong est voluptate prosciutto. Duis consectetur ut adipisicing, cillum doner brisket ut aliquip elit leberkas bacon picanha. Short loin drumstick tri-tip jerky, qui capicola sausage.\n" +
                    "\n" +
                    "Chicken est officia venison sirloin sint alcatra non tri-tip consectetur tenderloin pork loin corned beef cow jerky. Consequat ea qui tri-tip corned beef in veniam ground round reprehenderit occaecat. Ball tip salami kielbasa, flank frankfurter corned beef chuck. Voluptate filet mignon turkey sint cow spare ribs occaecat turducken ullamco mollit tempor consectetur.\n" +
                    "\n" +
                    "Pork loin in tri-tip ham id velit. Reprehenderit kielbasa ea, ham hock velit brisket occaecat boudin. Kevin et incididunt, meatball ipsum officia corned beef cillum est. Et burgdoggen qui, spare ribs incididunt consequat aliquip ut dolor do. Ribeye hamburger id aute sunt excepteur. Jerky buffalo jowl bacon elit pig, tri-tip commodo ullamco burgdoggen qui consequat ribeye labore duis. Ham hock corned beef ea, turducken swine hamburger leberkas ut nisi filet mignon salami bacon incididunt.\n" +
                    "\n" +
                    "Pariatur porchetta in ribeye. Consequat culpa in officia prosciutto, sunt chuck minim. Biltong reprehenderit shank ham. Cow laborum landjaeger quis, picanha est ut consequat deserunt pork fugiat culpa magna short loin.\n" +
                    "\n" +
                    "Ground round ipsum fugiat, picanha pig in bresaola ribeye pariatur pork chop strip steak ea. Shankle duis fatback, deserunt shank minim landjaeger dolore ullamco et. Dolor doner beef dolore consequat, chuck biltong. Excepteur shank biltong tenderloin minim. Landjaeger labore qui meatball. Dolore ham hock boudin meatloaf eiusmod chuck pork chop rump. Id chuck officia culpa kevin swine laboris bresaola beef fugiat.\n" +
                    "\n" +
                    "Pig commodo bacon, sunt drumstick kevin shoulder brisket exercitation pancetta hamburger pork sirloin. Nisi eu laborum short ribs. Pork dolore sausage consequat capicola t-bone chuck. Magna officia chicken ut deserunt, ham hock burgdoggen in turkey eiusmod rump flank. Ut pork loin sunt, rump picanha ground round labore meatloaf sint. Rump id laboris tail strip steak mollit nisi.\n" +
                    "\n" +
                    "In laborum qui dolor ad ground round. Short ribs bacon cupim pork loin, eiusmod strip steak biltong minim swine leberkas brisket tenderloin. Ad flank dolore sausage venison andouille sirloin ground round shoulder fatback capicola adipisicing short ribs. Bresaola frankfurter irure ground round, tongue in chuck sausage. Tongue tenderloin capicola, labore ut ut nulla leberkas qui.\n" +
                    "\n" +
                    "Consectetur sunt pork loin est cow short loin sirloin turkey pork. Velit ball tip aliquip, shoulder sausage sunt tempor tongue pig capicola sirloin do biltong shank picanha. Beef ribs incididunt pork chop do ground round magna. Voluptate drumstick reprehenderit frankfurter leberkas picanha tempor strip steak occaecat beef ribs pig ea hamburger. Sirloin anim ut esse kevin meatball magna. Corned beef meatloaf excepteur boudin proident.\n" +
                    "\n" +
                    "Shank ullamco nulla pork. Filet mignon cupidatat in meatloaf beef ribs officia corned beef chuck pariatur kielbasa. Do t-bone lorem biltong in. Dolor ullamco sausage, duis adipisicing sirloin et biltong. Flank ex cupidatat eu. Pork chop deserunt tempor anim.\n" +
                    "\n" +
                    "Consectetur ribeye occaecat pork loin boudin landjaeger pastrami sirloin cupidatat ham hock lorem. Enim officia prosciutto, salami dolore nostrud cillum sirloin swine pig elit laboris in. Commodo doner drumstick anim, ipsum ham swine non nisi porchetta beef ribs. Adipisicing swine meatball leberkas salami excepteur commodo rump. Id ea kevin buffalo, occaecat dolore pork esse prosciutto drumstick tenderloin ground round in minim ut. Pork aliquip culpa aute ea adipisicing, pork loin ribeye alcatra strip steak qui cupim. Capicola laborum salami ground round, pastrami tri-tip culpa officia.\n" +
                    "\n" +
                    "Short loin picanha tenderloin aute lorem jowl burgdoggen t-bone alcatra fatback doner in mollit brisket. Elit voluptate sunt culpa in. Ball tip qui adipisicing pork chop shoulder labore chicken ad turkey eu buffalo aliqua quis. Sint sirloin strip steak dolore landjaeger. Ullamco ut officia enim alcatra chuck corned beef beef ribs id. Ball tip cupidatat ad filet mignon, bresaola hamburger laborum minim ullamco aute."
    };

    @Test
    public void test() {
        for (String text : test_strings) {
            System.out.println("Original length: " + text.getBytes(UTF8.utf8).length);
            byte[] shrunk;
            {
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                Huffman.write(baos, text);
                shrunk = baos.toByteArray();
            }
            System.out.println("Compressed length: " + shrunk.length);
            {
                ByteArrayInputStream bais = new ByteArrayInputStream(shrunk);
                String expanded = Huffman.readToString(bais);
                if (expanded.length() != text.length() || !text.equals(expanded)) {
                    System.out.println(text);
                    System.out.println(expanded);
                    throw new IllegalStateException();
                }
            }
        }
    }
}
