/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdDDict
#define _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdDDict

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdDDict
 * Method:    createDDict
 * Signature: (JIZ)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdDDict_createDDict
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdDDict
 * Method:    releaseDDict
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdDDict_releaseDDict
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdDDict
