/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstd
#define _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstd

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstd
 * Method:    doCompress
 * Signature: (JIJII)I
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstd_doCompress
  (JNIEnv *, jobject, jlong, jint, jlong, jint, jint);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstd
 * Method:    doDecompress
 * Signature: (JIJI)I
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstd_doDecompress
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstd
 * Method:    frameContentSize0
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstd_frameContentSize0
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstd
 * Method:    compressBound0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstd_compressBound0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zstd_natives_NativeZstd
