/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx
#define _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx
 * Method:    allocateCtx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx_allocateCtx
  (JNIEnv *, jclass);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx
 * Method:    releaseCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx_releaseCtx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx
 * Method:    doCompressNoDict
 * Signature: (JJIJII)I
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx_doCompressNoDict
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jint);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx
 * Method:    doCompressRawDict
 * Signature: (JJIJIJII)I
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx_doCompressRawDict
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong, jint, jint);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx
 * Method:    doCompressCDict
 * Signature: (JJIJIJII)I
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdCCtx_doCompressCDict
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zstd_natives_NativeZstd
