/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflateDictionary
#define _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflateDictionary

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdInflateDictionary
 * Method:    digest0
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflateDictionary_digest0
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdInflateDictionary
 * Method:    release0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflateDictionary_release0
  (JNIEnv *, jclass, jlong);
  /*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdInflateDictionary
 * Method:    id0
 * Signature: (J)V
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflateDictionary_id0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflateDictionary
