/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater
#define _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater
 * Method:    allocateCtx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater_allocateCtx
  (JNIEnv *, jclass);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater
 * Method:    releaseCtx
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater_releaseCtx
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater
 * Method:    doDecompressNoDict
 * Signature: (JJIJI)I
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater_doDecompressNoDict
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater
 * Method:    doDecompressRawDict
 * Signature: (JJIJIJI)I
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater_doDecompressRawDict
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong, jint);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater
 * Method:    doDecompressCDict
 * Signature: (JJIJIJ)I
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater_doDecompressCDict
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdInflater
