/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdCDict
#define _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdCDict

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdCDict
 * Method:    createCDict
 * Signature: (JIIZ)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdCDict_createCDict
  (JNIEnv *, jclass, jlong, jint, jint, jboolean);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdCDict
 * Method:    releaseCDict
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdCDict_releaseCDict
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdCDict
