/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflateDictionary
#define _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflateDictionary

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflateDictionary
 * Method:    digest0
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflateDictionary_digest0
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflateDictionary
 * Method:    release0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflateDictionary_release0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflateDictionary
