/* DO NOT EDIT THIS FILE - it is machine generated */
//actually it's not, it was initially though
//easier to make this by hand lol
#include <jni.h>

#ifndef _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflater
#define _Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflater

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflater
 * Method:    allocate0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflater_allocate0
  (JNIEnv *, jclass);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflater
 * Method:    release0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflater_release0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflater
 * Method:    compress0
 * Signature: (JJIJIJI)I
 */
JNIEXPORT jint JNICALL Java_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflater_compress0
  (JNIEnv *, jclass, jlong, jlong, jint, jlong, jint, jlong, jint);

#ifdef __cplusplus
}
#endif

#endif //_Included_net_daporkchop_lib_compression_zstd_natives_NativeZstdDeflater
