/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeTest */

#ifndef _Included_NativeTest
#define _Included_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeTest
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeTest_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
