/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_daporkchop_lib_natives_NativeTest */

#ifndef _Included_net_daporkchop_lib_natives_NativeTest
#define _Included_net_daporkchop_lib_natives_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_daporkchop_lib_natives_NativeTest
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_NativeTest_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
