/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_daporkchop_lib_natives_zlib_NativeInflater */

#ifndef _Included_net_daporkchop_lib_natives_zlib_NativeInflater
#define _Included_net_daporkchop_lib_natives_zlib_NativeInflater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeInflater
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeInflater_load
  (JNIEnv *, jclass);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeInflater
 * Method:    init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_natives_zlib_NativeInflater_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeInflater
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeInflater_end
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeInflater
 * Method:    input
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeInflater_input
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeInflater
 * Method:    output
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeInflater_output
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeInflater
 * Method:    inflate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeInflater_inflate
  (JNIEnv *, jobject);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeInflater
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeInflater_reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
