/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_daporkchop_lib_natives_zlib_NativeDeflater */

#ifndef _Included_net_daporkchop_lib_natives_zlib_NativeDeflater
#define _Included_net_daporkchop_lib_natives_zlib_NativeDeflater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeDeflater
 * Method:    load
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeDeflater_load
  (JNIEnv *, jclass);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeDeflater
 * Method:    init
 * Signature: (IZ)J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_natives_zlib_NativeDeflater_init
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeDeflater
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeDeflater_end
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeDeflater
 * Method:    input
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeDeflater_input
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeDeflater
 * Method:    output
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeDeflater_output
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeDeflater
 * Method:    deflate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeDeflater_deflate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeDeflater
 * Method:    readBytes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_natives_zlib_NativeDeflater_readBytes
  (JNIEnv *, jobject);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeDeflater
 * Method:    writtenBytes
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_daporkchop_lib_natives_zlib_NativeDeflater_writtenBytes
  (JNIEnv *, jobject);

/*
 * Class:     net_daporkchop_lib_natives_zlib_NativeDeflater
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_daporkchop_lib_natives_zlib_NativeDeflater_reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
